- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: webservers
  become: yes
  tasks:
    - name: Install latest version of Apache
      apt: name=apache2 update_cache=yes state=latest
 
    - name: "UFW firewall allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
    - name: copy index.html file to the managed host
      copy:
        src: "{{ html_page_src }}"
        dest: "{{ html_page_dest }}"

